### ISSUE TITLE
[BUG] Navigation bar refreshing the whole page

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [Arquisoft/viade_en1b#36]
**Describe the bug**
The navigation bar refreshes all the page when clicked.

**To Reproduce**
1. Open the profiler of the react-dev-tools.
2. Click on the record button.
3. Click on the navbar.
4. Notice how you are not able to record because the entire page is refresh.

**Expected behavior**
The navigation bar should not be refreshed, just the other elements of the page.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Google Chromium
 - Version: 79.0.3945.130

**Additional context**
I noticed the problem when executing the built-in react-dev-tools profiler to record some actions.
To fix we may use [react-router-bootstrap](https://github.com/react-bootstrap/react-router-bootstrap)

**Comment by themrcesi** [comment]
Ready to close? @alvarezGarciaMarcos

**Comment by alvarezGarciaMarcos** [comment]
It is supposed to be closed by a commit, but yeah, you can go ahead an close it 🤣

**Comment by themrcesi** [comment]
Done!
