### ISSUE TITLE
[STYLING] Add logo of the app to the Navbar

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [Arquisoft/viade_en1b#37]
# What is the target component?
The component affected will be the Navigation bar.
# What is missing?
The logo of the application is not present in the navigation bar.
# Expected style
The logo should be displayed in the left side of the nav.

**Comment by themrcesi** [comment]
@alvarezGarciaMarcos ready to close?

**Comment by alvarezGarciaMarcos** [comment]
Yeah, I didn't added the command in the description of the issue, sorry for that 🙏.
