### ISSUE TITLE
[BUG] Routing and gh-pages

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [Arquisoft/viade_en1b#45]
**Describe the bug**
The deployment of the application is not working due to react-router. We have to fix it to have a functional application in the deployment.

**To Reproduce**
1. Go to the [deployment page](https://arquisoft.github.io/viade_en1b/)
2. Get into the console and see the logs

**Expected behavior**
The app should be displayed perfectly.

**Comment by themrcesi** [comment]
Working on it!

**Comment by themrcesi** [comment]
@labra do you remember the other group that managed to solve this problem? We have tried the main solutions available on the web, but we don´t achieve it.

**Comment by labra** [comment]
I don't remember now, but I think they managed to solve it following [this article](https://www.pluralsight.com/guides/deploying-react-app-with-react-router-to-gh-pages)
