### ISSUE TITLE
[BUG] Manually routing

### ISSUE THREAD

**Issue by themrcesi** [Arquisoft/viade_en1b#47]
**Describe the bug**
Some routes such as /dashboard, /myProfile, etc... should be only available when the user is logged in. However, if we write in the URL the path for the route, we can actually access those routes without being logged in.

**To Reproduce**
1. Just don´t be logged in.
2. Write in the URL one invalid path (ex: /dashbaord)
3. You´re redirected 

**Expected behavior**
We shouldn´t be allowed to be redirected to some routes when we are not logged in.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.132

**Comment by alvarezGarciaMarcos** [comment]
For this I purpose that we check middlewares out, I think it is the correct approach for this kind of problems.

**Comment by themrcesi** [comment]
@alvarezGarciaMarcos I think I have another approach, using the solid components <LoggedIn> and <LoggedOut>.

**Comment by alvarezGarciaMarcos** [comment]
What is the other alternative you are proposing @themrcesi . Also, I think we should create an error page for when a user is trying to access a page without being logged in.

**Comment by themrcesi** [comment]
That page is already created :) PageNotFound.js, a very simple one.

Using the <LoggedIn> and <LoggedOut> components of react-solid, we can define two diferent ways of routing, one for logged users and other for non logged users.
