### ISSUE TITLE
[FEATURE REQUEST] Restricted file extensions when uploading files

### ISSUE THREAD

**Issue by themrcesi** [Arquisoft/viade_en1b#48]
In the upload route component, we are allowing to upload any file when we actully want to upload images or videos.

**Describe the solution you'd like**
We should only allow uploads of files with the correct extensions.

**Describe alternatives you've considered**
I found this component, that seem to be easy to implement and allow us to set the allowed extensions: '@progress/kendo-react-upload'

**Comment by themrcesi** [comment]
It´d be nice if we could manage this to the next week. 

If not, we pospone it for next deliveries :) What do you think?

**Comment by alvarogarinf** [comment]
I think we could manage to solve this to next week

**Comment by alvarogarinf** [comment]
I have just created a pull request with this functionality added
