### ISSUE TITLE
[BUG] Routing bug

### ISSUE THREAD

**Issue by themrcesi** [Arquisoft/viade_en1b#50]
In the deployed version, when we log out of the application, we are redirected to the homepage of the course.

**To Reproduce**
1. Log in
2. Log out
3. See error: redirected to the homepage instead of "#/login"

**Expected behavior**
When we log out the application, we should be redirected to "#/login".

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80.0.3987.132

**Comment by InigoGutierrez** [comment]
Also, when going to the previous page after this happens, a view of the application without the navigation bar is shown.

**Comment by themrcesi** [comment]
@InigoGutierrez that happens because of another problem commented in this issue #47

**Comment by themrcesi** [comment]
Maybe we can use a normal button adding ourselves the logic for logging out instead of using the LogOut button of react-solid.

**Comment by themrcesi** [comment]
More or less fixed: it refreshes and goes first to /dashboard but at least it works.
