### ISSUE TITLE
[FEATURE] Dark theme

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [Arquisoft/viade_en1b#53]
**Is your feature request related to a problem? Please describe.**
Currently the only way to change the theme of the application is modifiying the source code. Si what I would like is to add a simple toggle switch to toggle between a _colorful_ theme to a _dark_ one. It is a feature that I'm starting to see in a lot of websites now a days.

**Describe the solution you'd like**
Adding a toggle switch in the navigation bar to switch between themes.

**Comment by themrcesi** [comment]
I´d also include a theme for colour blidness people!

**Comment by alvarezGarciaMarcos** [comment]
I like how it sounds! Could you (or anyone interested in the team) do some research about what colors should we use with color blind people? I think it would be a cool feature!

**Comment by lamasumas** [comment]
We can also create a Settings page so in the future we can add more customizations like laguage selection,...

**Comment by InigoGutierrez** [comment]
Regarding color blindness, AFAIK, blue and orange is a good combo. It is easy to have high contrast between both, which helps a lot for people with total color blindness, and most other people can still percieve blue. There are several articles out there proposing color palettes which take into account colorblind people, like this one: https://venngage.com/blog/color-blind-friendly-palette/

**Comment by themrcesi** [comment]
Close it? @alvarezGarciaMarcos

**Comment by alvarezGarciaMarcos** [comment]
Yes, proceeding!
